version: '3'
services:
  userservice:
    image: haibane46/minimalist-user-service
    container_name: userservice
    ports:
      - "9001:9000"
  user-nginx:
    build: ./UserService/nginx
    ports:
      - "8081:8080"
    depends_on:
      - userservice
      
  categoryservice:
    image: haibane46/minimalist-category-service
    container_name: categoryservice
    ports:
      - "9002:9000"
  category-nginx:
    build: ./CategoryService/nginx
    ports:
      - "8082:8080"
    depends_on:
      - categoryservice
      
  itemservice:
    image: haibane46/minimalist-item-service
    container_name: itemservice
    ports:
      - "9003:9000"
  item-nginx:
    build: ./ItemService/nginx
    ports:
      - "8083:8080"
    depends_on:
      - itemservice

  frontend:
    image: haibane46/minimalist-frontend
    container_name: frontend
    ports:
      - "8080:8080"

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data:
