version: '3'
services:
  userservice:
    build: ./UserService
    container_name: userservice
    ports:
      - "9001:9000"
      
  categoryservice:
    build: ./CategoryService
    container_name: categoryservice
    ports:
      - "9002:9000"
      
  itemservice:
    build: ./ItemService
    container_name: itemservice
    ports:
      - "9003:9000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data:
