version: '3'
services:

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/UserService/:/var/www/UserService
      - ./apps/InventoryService/:/var/www/InventoryService
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/ssl/
    networks:
      - app-network

  userservice:
    build:
      context: apps/UserService
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: userservice
      SERVICE_TAGS: dev
    working_dir: /var/www/UserService
    volumes:
      - ./apps/InventoryService/:/var/www/UserService
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  inventoryservice:
    build:
      context: apps/InventoryService
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: inventoryservice
      SERVICE_TAGS: dev
    working_dir: /var/www/InventoryService
    volumes:
      - ./apps/InventoryService/:/var/www/InventoryService
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: minimalist_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/var/lib/mysql/my.cnf
    networks:
      - app-network
  
  frontend:
    image: haibane46/minimalist-frontend
    container_name: frontend
    ports:
      - "8001:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
