name: MinimaList CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_user_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Push User Service
      run: |
        cd UserService
        docker build -t haibane46/minimalist-user-service .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push haibane46/minimalist-user-service

  build_inventory_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Push Inventory Service
      run: |
        cd InventoryService
        docker build -t haibane46/minimalist-inventory-service .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push haibane46/minimalist-inventory-service


  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Push Frontend
      run: |
        cd frontend
        docker build -t haibane46/minimalist-frontend .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push haibane46/minimalist-frontend
