name: MinimaList CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_user_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Push User Service
      run: |
        cd UserService
        docker build -t haibane46/user-service .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push haibane46/minimalist-user-service

  build_category_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Push Category Service
      run: |
        cd CategoryService
        docker build -t haibane46/category-service .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push haibane46/minimalist-category-service

  build_item_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Push Item Service
      run: |
        cd ItemService
        docker build -t haibane46/item-service .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push haibane46/item-service

  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Push Frontend
      run: |
        cd frontend
        docker build -t haibane46/frontend .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push haibane46/minimalist-frontend 
